// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZzBCZD6RS9WSwcGLXEbJDLMKvnn3d7Y',
    appId: '1:967168672492:web:ddd9d4ac41a3619939dbc9',
    messagingSenderId: '967168672492',
    projectId: 'blog-app-daa98',
    authDomain: 'blog-app-daa98.firebaseapp.com',
    storageBucket: 'blog-app-daa98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpbaJ863tWPI87JjRMzZeQhwoiCC9Oal4',
    appId: '1:967168672492:android:a0600efa35346ec039dbc9',
    messagingSenderId: '967168672492',
    projectId: 'blog-app-daa98',
    storageBucket: 'blog-app-daa98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnw7_XRBhgr2SCa-fAOoduXkAswpmUHe4',
    appId: '1:967168672492:ios:2125e21dbc4eacbc39dbc9',
    messagingSenderId: '967168672492',
    projectId: 'blog-app-daa98',
    storageBucket: 'blog-app-daa98.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnw7_XRBhgr2SCa-fAOoduXkAswpmUHe4',
    appId: '1:967168672492:ios:2125e21dbc4eacbc39dbc9',
    messagingSenderId: '967168672492',
    projectId: 'blog-app-daa98',
    storageBucket: 'blog-app-daa98.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgZzBCZD6RS9WSwcGLXEbJDLMKvnn3d7Y',
    appId: '1:967168672492:web:5ba010fb737253bb39dbc9',
    messagingSenderId: '967168672492',
    projectId: 'blog-app-daa98',
    authDomain: 'blog-app-daa98.firebaseapp.com',
    storageBucket: 'blog-app-daa98.appspot.com',
  );
}
